# Conexion a la misma base de datos del CLI
spring.datasource.url=jdbc:mysql://localhost:3306/sd3
spring.datasource.username=root
spring.datasource.password=Srot405@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - none significa que NO modifica la tabla existente del CLI
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT - cambia este secret por uno seguro en produccion
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e4f13b7523f45b8b8b6c2f9d1
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Puerto
server.port=8080
